# Generated by Django 3.0.3 on 2020-02-14 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_auto_20200214_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('X', 'Prefer not to mention')], default='X', max_length=50),
        ),
    ]
